### ISSUE TITLE
Doesn't build with asyn 4.33

### ISSUE THREAD

**Issue by aderbenev** [epicsdeb/calc#1]
Now fails to satisfy dependencies after [asyn upstream import](https://github.com/epicsdeb/asyn/commit/a437ff357c175b50da55efdda74a1c1e30af8f1e):

```
rtems-calc-mvme5500 : Depends: rtems-asyn-mvme5500 (<= 4.31-9999) but 4.33-2.1 is to be installed.
rtems-calc-mvme3100 : Depends: rtems-asyn-mvme3100 (<= 4.31-9999) but 4.33-2.1 is to be installed.
rtems-calc-mvme2100 : Depends: rtems-asyn-mvme2100 (<= 4.31-9999) but 4.33-2.1 is to be installed.
```

Noticed when building the recently updated [stream](https://github.com/epicsdeb/stream). I guess there are other dependent packages which will fail in the same manner.

**Comment by mark0n** [comment]
I just checked the build log of our Jenkins server and it looks like the calc package builds fine against the Asyn 4.33-2 package. Are building in a clean-room environment (e.g. pbuilder)? The messages sound like you have an old version of rtems-calc-mvme* installed which prevents rtems-asyn-mvme* from being upgraded automatically.

**Comment by aderbenev** [comment]
It is being built in a clean pbuilder image yes, where asyn 4.33 is an installation candidate. I thought the problem is due to something in debian/control when calc says that it wants an older version of asyn (<= 4.31-9999) but only the new one is available (4.33), yet I see nothing which would control that preference. I shall check that asyn 4.33 is what's installed in the pbuilder image, although I'm certain it is the case...

**Comment by aderbenev** [comment]
I checked and 4.33 is the installation candidate in the pbuilder image, and there is no other version to install. Apparently the origin is somewhere in the RTEMS check summarized [here](https://github.com/epicsdeb/epics-debhelper/blob/5678deb7ac2270e0845fb7daaef2105d114ba98c/dh_rtems#L28), yet I don't know how 4.31 pops up for calc - and why getting the new upstream for calc actually fixes it. I shall try building the present upstream (3.6) again and inspect the output more closely.

**Comment by aderbenev** [comment]
Okay, never underestimate the "plug it out - plug it back in" approach. Wiped out stream and calc, asyn is 4.33-2. Calc 3.6.1-2 was built successfully, and stream 2.7.7-1 built as well. I wanted to grab some evidence from the recent log, but there is no issue I can reproduce. Apparently something glitched and convinced me that getting the recent upstream fixed things.

@mark0n, do you happen to have the new calc in your environment to bump this one's version maybe? There are my pull requests but no reason to breed variety.

Closing this meanwhile, thanks for your input.
